apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://localhost:5672"
    - name: protocol
      value: amqp
    - name: hostname
      value: localhost
    - name: username
      value: guest
    - name: password
      value: guest
    - name: durable
      value: true
    - name: deletedWhenUnused
      value: false
    - name: autoAck
      value: false
    - name: deliveryMode
      value: 2
    - name: requeueInFailure
      value: false
    - name: prefetchCount
      value: 10
    - name: reconnectWait
      value: 3s
    - name: concurrencyMode
      value: parallel
    - name: publisherConfirm
      value: true
    - name: enableDeadLetter
      value: true
