version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "#SqlHardPass1"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - devnet

volumes:
  sqlvolume:

networks:
  devnet: