<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Orionexx.Core.Shared\Orionexx.Core.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="..\..\Shared\Orionexx.Protos.Shared\**/*.proto" GrpcServices="Server" Link="Protos\%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>

</Project>
