name: pr_check_ci.yml
on:
  pull_request:
    branches: [ "main" ]
env:
  DOTNET_VERSION: '9.0.x'
  BUILD_CONFIGURATION: 'Release'
  
jobs:
  pr-build:
    name: 🧪 PR Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Solution
        run: dotnet restore Orionexx.sln

      - name: Build Solution
        run: dotnet build Orionexx.sln --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Run tests with coverage
        run: dotnet test Orionexx.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory TestResults

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: '**/TestResults/*/coverage.cobertura.xml'